Add Contributors guidance for Dioptra
usnistgov/dioptra pull request #150
Opened 2023-03-07 18:01 UTC by jkglasbrenner

Closes #80 
Closes #81

2023-03-08 13:05 UTC, hbooth requested changes
Just the two comments and it should be ready to go.

2023-03-08 13:05 UTC, hbooth commented on CONTRIBUTING.md
> +# Feature Requests
Perhaps be a sub-header (in other words needs another '#' character)?

2023-03-08 13:05 UTC, hbooth commented on CONTRIBUTING.md
> +# Commit Style Guide
I think may also be a sub-heading too. Either that, or the next one should be a top-level header, although I think sub-heading may make more sense.

2023-03-09 21:36 UTC, jkglasbrenner commented
@hbooth I looked at the Markdown headers you pointed out and agree they were at the wrong level. After looking at CONTRIBUTING.md again in light of your feedback, here's the new subject heading hierarchy:

- Criteria for Contributions and Feedback
- Contributor Responsibilities
- Question or Problem?
- Submitting Issues
    - Bugs
    - Feature Requests
- Code Submission Guidelines
    - Development Workflow
    - Commit Style Guide
        - Squashing
    - Code Reviewing Guide

I moved the squashing section under Commit Style Guide since that seemed to make more sense, and kept Code Reviewing Guide as a sub-heading up Code Submission Guidelines.

Also, I didn't notice that we had more than one `#` header in the file, the convention is to reserve `#` for the title and only use it once. I also fixed that up.

I think it looks good now, let me know if you agree and we can get this merged.

2023-03-09 21:40 UTC, hbooth approved these changes
Agreed and everything looks good to me.

2023-03-09 23:06 UTC, merged