Refactor: add tar help function to replace use of make and move utils to scripts folder
usnistgov/dioptra pull request #172
Opened 2023-03-23 18:58 UTC by alexb1200

Towards resolving #163 and #164, still need to change example notebooks and test changes.

2023-03-23 22:57 UTC, jkglasbrenner requested changes
I did a quick review of the merge request and left comments and requested some changes. Please let me know if you have any questions.

2023-03-23 22:57 UTC, jkglasbrenner commented on examples/scripts/client.py
> +def tar_helper(
Style comment:

The convention in the repo is to name functions using action verbs and use nouns for classes. This should be renamed to something like `create_tar` or `make_tar`.

2023-03-23 22:57 UTC, jkglasbrenner commented on examples/scripts/client.py
> +    Args:
Style comment:

Google doc-strings should have a blank line separating each section.

2023-03-23 22:57 UTC, jkglasbrenner commented on examples/scripts/client.py
> +    os.chmod(tarball_path, 436)
I don't think `os.chmod` is necessary here, try removing it and confirm that nothing is broken.

2023-03-23 22:57 UTC, jkglasbrenner commented on examples/scripts/utils.py
This file shouldn't be moved in this merge, please undo.

2023-03-23 22:57 UTC, jkglasbrenner commented on examples/scripts/client.py
The `DioptraClient` class should be in the `client.py` file by itself, since client implies code that talks to a server of some kind. The new function for creating tar files can be extracted into `examples/scripts/utils.py`.

2023-03-27 15:17 UTC, lbarbMITRE approved these changes
LGTM after changes

2023-04-04 17:08 UTC, jkglasbrenner approved these changes
LGTM after final edits

2023-04-04 17:08 UTC, merged