examples: feature squeezing update
usnistgov/dioptra pull request #192
Opened 2023-05-08 17:28 UTC by jtsextonMITRE

Cleaned up and updated the feature squeezing example to use the new scripts in the examples folder, and checked that the stuff still runs.

2023-05-10 13:25 UTC, andrewhand reviewed
Core code unchanged. Expected changes where to new Paths and reworking make to py functionss/plugs. Some removes of extraneous code such as imports copied+paste from templates. Code ran clean.

2023-06-01 15:38 UTC, jkglasbrenner requested changes

2023-06-01 15:38 UTC, jkglasbrenner commented on examples/task-plugins/dioptra_custom/feature_squeezing/tensorflow_plugin.py
The code in this file seems to be a duplicate/earlier version of the built-in `dioptra_builtins/data/tensorflow.py`, the entrypoint scripts can be updated to just use the builtin versions instead and this file can be removed.

2023-06-01 15:38 UTC, jkglasbrenner commented on examples/tensorflow-mnist-feature-squeezing/src/data.py
This is old code that was migrated to a task plugin and can be removed.

2023-06-01 15:38 UTC, jkglasbrenner commented on examples/tensorflow-mnist-classifier/demo.ipynb
This notebook doesn't need to be changed, so undo this change before merging.

2023-06-01 15:38 UTC, jkglasbrenner commented on examples/tensorflow-mnist-feature-squeezing/src/feature_squeeze.py
The if/else logic in lines 147–150 can be removed, as the builtin init_rng task plugin does the same thing.

2023-06-01 15:38 UTC, jkglasbrenner commented on examples/tensorflow-mnist-feature-squeezing/src/train.py
The mlflow.autolog() function on line 158 should be deleted as it's functionality isn't compatible with how we've constructed the entrypoints.

2023-06-01 15:38 UTC, jkglasbrenner commented on examples/tensorflow-mnist-feature-squeezing/demo.ipynb
In import code cell, for EXPERIMENT_NAME variable remove the username prefix and append `mnist_` as the prefix instead.

2023-06-01 15:38 UTC, jkglasbrenner commented on examples/tensorflow-mnist-feature-squeezing/demo.ipynb
Make the model training non-optional (so remove the Markdown blocks and just keep executable code blocks), and change the model registry name to something other than `mnist_<architecture>`, since otherwise it conflicts with the models created in the tensorflow-mnist-classifier example.

2023-06-01 15:38 UTC, jkglasbrenner commented on examples/tensorflow-mnist-feature-squeezing/demo.ipynb
Since the input parameters for the different attacks are listed, verify that the parameter names and their default values match what is in MLproject and the custom task plugins.

2023-06-01 15:38 UTC, jkglasbrenner commented on examples/tensorflow-mnist-feature-squeezing/demo.ipynb
Remove empty code block at the bottom of the notebook.

2023-06-08 16:56 UTC, jkglasbrenner approved these changes

2023-06-08 16:56 UTC, jkglasbrenner approved these changes

2023-06-08 16:56 UTC, merged