examples:  update tensorflow backdoor poisoning notebooks to new deployment method
usnistgov/dioptra pull request #193
Opened 2023-05-09 19:16 UTC by alexb1200

Towards closing #152 

- Added new deployment instructions and documentation to README
- Moved custom plugins to  dioptra/examples/task-plugins/custom-poisoning_plugins
- Moved MLproject to src folder
- Modified demo-mnist-poison-backdoor-adv-embedding, demo-mnist-poison-backdoor-baseline, demo-mnist-poison-backdoor-clean-label to use the new scripts. 
- Removed unused files in example folder

2023-05-11 16:31 UTC, jtsextonMITRE reviewed
`src/train.py`, 
`src/train_with_madry_pgd_defense.py`, 
`src/spatial_smoothing.py`, 
`src/jpeg_compression.py`, 
`src/gen_poison_model.py`, 
`src/gaussian_augmentation.py` 
 
should have the `load_dataset_from_mlruns` functionality extracted to a task plugin or just added to into the workflow if all that functionality already exists.

2023-05-11 16:38 UTC, jtsextonMITRE commented
`response_gen_poison_le_net_train_clean` <- This code block in demo-mnist-poison-backdoor-clean-label.ipynb should have

`depends_on=response_le_net_train_robust` instead of `depends_on=response_le_net_train`

2023-05-11 16:39 UTC, jtsextonMITRE commented
`response_infer_pos_model_clean` <- This code block has a mismatch between the depends_on (`response_le_net_train_backdoor_model_clean`) and the run_id (`response_gen_poison_le_net_test`)being used.

2023-05-11 16:42 UTC, jtsextonMITRE commented
`response_infer_reg_model` <- This code block has a mismatch between the depends_on (`response_le_net_train`) and the run_id (`response_gen_poison_le_net_test`) being used.

2023-05-11 16:46 UTC, jtsextonMITRE commented
The `demo-mnist-poison-backdoor-clean-label.ipynb` notebook has a title of Adversarial Embedding

2023-05-11 17:09 UTC, jtsextonMITRE commented
We should add a comment near `response_gen_poison_le_net_train_clean` in `...clean-label.ipynb` that the poison fraction, the test dataset or the batch size being small can result in errors due to ART potentially randomly selecting 0 images to poison.

2023-05-31 15:57 UTC, jkglasbrenner requested changes

2023-05-31 15:57 UTC, jkglasbrenner commented on examples/tensorflow-backdoor-poisoning/demo-mnist-poison-backdoor-adv-embedding.ipynb
Remove the USERNAME = "" from the code block at the beginning and fix EXPERIMENT_NAME to reflect change.

2023-05-31 15:57 UTC, jkglasbrenner commented on examples/tensorflow-backdoor-poisoning/demo-mnist-poison-backdoor-adv-embedding.ipynb
Remove the MLFlow query section at the end of the notebook.

2023-05-31 15:57 UTC, jkglasbrenner commented on examples/tensorflow-backdoor-poisoning/demo-mnist-poison-backdoor-adv-embedding.ipynb
This can be applied to all 3 notebooks.

2023-05-31 15:57 UTC, jkglasbrenner commented on examples/tensorflow-backdoor-poisoning/demo-mnist-poison-backdoor-adv-embedding.ipynb
This can be applied to all 3 notebooks.

2023-05-31 15:57 UTC, jkglasbrenner commented on examples/tensorflow-backdoor-poisoning/src/gen_poison_model.py
Remove unused `download_data_archive` function from the bottom of the file.

2023-05-31 15:57 UTC, jkglasbrenner commented on examples/tensorflow-backdoor-poisoning/src/train_with_madry_pgd_defense.py
Remove unused download_data_archive function from the bottom of the file.

2023-05-31 15:57 UTC, jkglasbrenner commented on examples/tensorflow-backdoor-poisoning/src/MLproject
> +  train_old:
If this isn't used in the notebooks, it can be removed from MLproject.

2023-06-07 19:43 UTC, jkglasbrenner approved these changes
All of the changes we discussed in my last code review have been addressed. The GitHub Actions build failure is unrelated to the changes here (the failure is due to a change in the underlying VMs hosting the public runners, they have 3GB less storage space than before, which broke the pytorch-gpu builds). Approving, and proceeding to squash and merge.

2023-06-07 22:31 UTC, merged