feat: implement v1 schemas for MLFlow Runs
usnistgov/dioptra pull request #409
Opened 2024-03-01 21:49 UTC by etrapnell-nist

2024-03-06 20:44 UTC, alexb1200 commented on src/dioptra/restapi/v1/mlflow_runs/controller.py
> +    def post(self):
The swagger docs show this as the input for POST
![image](https://github.com/usnistgov/dioptra/assets/52888850/59ffef99-a8ad-4c33-8b5e-9d9f6fe96227)
Whereas the google doc shows
![image](https://github.com/usnistgov/dioptra/assets/52888850/7bd81706-71c7-497c-aefe-35852c996669)
Should data in  `MLFlowRunSchema` be marked dump only or should the google api doc be altered?

2024-03-06 20:47 UTC, alexb1200 commented on src/dioptra/restapi/v1/mlflow_runs/schema.py
> +class MLFlowRunSchema(MLFlowRunBaseSchema):  # type: ignore
This may need to change based on my other comment.

2024-03-06 20:48 UTC, alexb1200 requested changes
Besides that one discrepancy between the google doc and the swagger docs it all looks good to me. Once that's resolved please tag either James or Keith for a final once over before we merge.

2024-03-12 14:19 UTC, alexb1200 commented on src/dioptra/restapi/v1/mlflow_runs/schema.py
> +    data = fields.Dict(
This field can be removed. After that, this should be good to go!

2024-03-12 14:19 UTC, alexb1200 reviewed
Besides that one discrepancy between the google doc and the swagger docs it all looks good to me. Once that's resolved please tag either James or Keith for a final once over before we merge.

2024-03-13 15:17 UTC, etrapnell-nist commented
I've removed the data attribute and updated the Google Doc. It should be ready for review now @keithmanville.

2024-03-15 17:30 UTC, merged