feat: implement v1 schemas for models
usnistgov/dioptra pull request #412
Opened 2024-03-01 22:21 UTC by mtrapnell-nist

This is blocked until #410 is merged. Also include model schemas and endpoints for version endpoints that are not in the original API map.

2024-03-29 19:32 UTC, alexb1200 approved these changes
LGTM

2024-04-09 14:09 UTC, keithmanville commented
This PR needs additional work due to changes in the ERD. Models are now a Resource. Assigning myself to make these changes.

2024-04-23 15:45 UTC, jkglasbrenner requested changes

2024-04-23 15:45 UTC, jkglasbrenner commented on src/dioptra/restapi/v1/models/schema.py
> +        data_keyt="artifact",
Mispelling: `data_keyt` -> `data_key`

2024-04-23 15:45 UTC, jkglasbrenner commented on src/dioptra/restapi/v1/models/schema.py
> +    )
Missing a `load_only=True` so that it doesn't show up on GETs

2024-05-03 19:31 UTC, merged