Add v1 users schema and controller stubs
usnistgov/dioptra pull request #451
Opened 2024-04-19 19:54 UTC by keithmanville

Replacing #438 with PR for branch on `usnistgov/dioptra` instead of fork `pscemama-mitre/dioptra`

2024-04-19 19:55 UTC, keithmanville commented
This looks good to me. Recommend squashing commits and merging.

2024-04-23 15:18 UTC, jkglasbrenner requested changes

2024-04-23 15:18 UTC, jkglasbrenner commented on src/dioptra/restapi/v1/users/schema.py
> +    memberOf = fields.Nested(
Let's change this field to `groups` (also `attribute="groups"`).

2024-04-23 15:18 UTC, jkglasbrenner commented on src/dioptra/restapi/v1/users/schema.py
> +
Also needs a `confirmPassword` field for initial user registration, so its `load_only=True`.

https://github.com/usnistgov/dioptra/blob/60af0a6aac3af7e4e9a47e16afa0e6877af9f05f/src/dioptra/restapi/v0/user/schema.py#L49-L55

2024-04-23 15:18 UTC, jkglasbrenner commented on src/dioptra/restapi/v1/users/controller.py
> +    @responds(schema=UserSchema, api=api)
The current PUT should return the same fields that a /current GET provides.

```suggestion
    @responds(schema=UserCurrentSchema, api=api)
```

2024-04-23 15:18 UTC, jkglasbrenner commented on src/dioptra/restapi/v1/users/schema.py
> +
Also needs a `confirmNewPassword` field for initial user registration, so its `load_only=True`.

https://github.com/usnistgov/dioptra/blob/60af0a6aac3af7e4e9a47e16afa0e6877af9f05f/src/dioptra/restapi/v0/user/schema.py#L49-L55

2024-04-25 16:47 UTC, pscemama-mitre commented
Getting this output when trying to run

```bash
python3 -m tox run -e black,isort,flake8,mypy,gitlint -- src/dioptra
```

```bash
src/dioptra/restapi/v1/users/schema.py:141:90: B950 line too long (89 > 80 characters)
src/dioptra/rq/tasks/run_mlflow.py:206:17: B909 editing a loop's mutable iterable often leads to unexpected results/bugs
src/dioptra/sdk/object_detection/bounding_boxes/postprocessing/tensorflow_backend/confluence.py:262:25: B909 editing a loop's mutable iterable often leads to unexpected results/bugs
src/dioptra/sdk/object_detection/bounding_boxes/postprocessing/tensorflow_backend/confluence.py:265:25: B909 editing a loop's mutable iterable often leads to unexpected results/bugs
src/dioptra/sdk/object_detection/bounding_boxes/postprocessing/tensorflow_backend/confluence.py:292:21: B909 editing a loop's mutable iterable often leads to unexpected results/bugs
src/dioptra/sdk/object_detection/bounding_boxes/postprocessing/tensorflow_backend/confluence.py:293:21: B909 editing a loop's mutable iterable often leads to unexpected results/bugs
src/dioptra/sdk/object_detection/bounding_boxes/postprocessing/tensorflow_backend/confluence.py:294:21: B909 editing a loop's mutable iterable often leads to unexpected results/bugs
src/dioptra/sdk/object_detection/bounding_boxes/postprocessing/tensorflow_backend/confluence.py:337:25: B909 editing a loop's mutable iterable often leads to unexpected results/bugs
src/dioptra/sdk/object_detection/bounding_boxes/postprocessing/tensorflow_backend/confluence.py:354:17: B909 editing a loop's mutable iterable often leads to unexpected results/bugs
src/dioptra/task_engine/run_experiment.py:148:13: B909 editing a loop's mutable iterable often leads to unexpected results/bugs
src/dioptra/task_engine/util.py:317:9: B909 editing a loop's mutable iterable often leads to unexpected results/bugs
```

@keithmanville  @jkglasbrenner I believe I'm doing something wrong?

2024-05-03 16:35 UTC, pscemama-mitre commented
@keithmanville this is the question I had (also cc @jkglasbrenner)

Right now it seems to me like we allow a User's password to be changed via ID (and knowing the old password).

We have both `/current/password` and `id/password`. Following this, why do we not allow a User's email/username to be changed via ID? 

Or, why do we even bother having a User's password being able to be changed via ID (and not current?)?

2024-05-03 19:25 UTC, keithmanville commented
I believe the intent behind `/users/{id}/password` is for a user to change their password without being logged in if their password has expired, or they are locked out for some other reason. Other updates to their profile (like username or email changes) should happen once logged in and they are now the current user.

2024-05-03 19:38 UTC, merged