[WIP] V1 plugin parameter types unit tests
usnistgov/dioptra pull request #461
Opened 2024-05-09 20:37 UTC by mtrapnell-nist

The plugin parameter type unit tests in this PR make use of the fixtures/actions/helpers that were separated out into conftest.py, actions.py and helpers.py.

2024-05-23 02:41 UTC, keithmanville requested changes
I think this is in a state where we can start to develop the service layer against these tests.

2024-05-23 02:41 UTC, keithmanville commented on tests/unit/restapi/lib/actions.py
> +    group_id: int,
should have a `description` as well. Present in ORM and added to schema by #460

2024-05-23 02:41 UTC, keithmanville commented on tests/unit/restapi/v1/conftest.py
> +    # TODO: Move this to conftest.py after rebasing off dev
Looks like this happened. Comment can be removed.

2024-05-23 02:41 UTC, keithmanville commented on tests/unit/restapi/v1/conftest.py
> +    )
actions return `TestResponse` but the fixture should return a `dict`, so append `.get_json()` to each `create_plugin_parameter_type` call here.

2024-05-23 02:41 UTC, keithmanville commented on tests/unit/restapi/v1/test_pluginparametertypes.py
> +    client: FlaskClient, id: int, new_name: str, new_structure: dict[str, Any]
add `description`

2024-05-23 02:41 UTC, keithmanville commented on tests/unit/restapi/v1/test_pluginparametertypes.py
> +    ].get_json()
`.get_json()` can be removed once fixture is update.

2024-05-23 02:41 UTC, keithmanville commented on tests/unit/restapi/v1/test_pluginparametertypes.py
> +    ].get_json()
Needs to be updated throughout the tests.

2024-05-23 02:41 UTC, keithmanville commented on tests/unit/restapi/v1/test_pluginparametertypes.py
> +    start_name = plugin_param_type1["id"]
should be "name" not "id"

2024-05-23 02:41 UTC, keithmanville commented on tests/unit/restapi/v1/test_pluginparametertypes.py
> +        group_id=auth_account["default_group_id"],
need to access this through `registered_users`

2024-05-23 02:41 UTC, keithmanville commented on tests/unit/restapi/v1/test_pluginparametertypes.py
> +        group_id=auth_account["default_group_id"],
use first `registered_user`

2024-05-23 02:41 UTC, keithmanville commented on tests/unit/restapi/v1/test_pluginparametertypes.py
> +        group_id=auth_account["default_group_id"],
@jkglasbrenner We changed `auth_account` to return the response from login. Do we want to change it back? Makes more sense for many of these tests that need the currently logged in user to not need to go through the full list of registered users.

2024-05-23 14:33 UTC, andrewhand requested changes
Just a review of actions and conftest needed to merge these files into dev for use in Plugin tests. Did not review the test files for this endpoint.

2024-05-23 14:33 UTC, andrewhand commented on tests/unit/restapi/lib/actions.py
> +def create_plugin_parameter_type(
```suggestion
def register_plugin_parameter_type(
```
Change create to register to keep established naming schema.

2024-05-23 14:33 UTC, andrewhand commented on tests/unit/restapi/lib/actions.py
> +    structure: dict[str, Any] | None = None,
> should have a `description` as well. Present in ORM and added to schema by #460

```suggestion
    client: FlaskClient,
    name: str,
    group_id: int,
    structure: dict[str, Any] | None = None,
    description: str | None = None,
```
Adding description as mentioned.

2024-05-23 14:33 UTC, andrewhand commented on tests/unit/restapi/lib/actions.py
> +        payload["structure"] = structure
> should have a `description` as well. Present in ORM and added to schema by #460
```suggestion
    payload = {"name": name, "group_id": group_id}

    if structure:
        payload["structure"] = structure
        
    if description:
        payload["description"] = description
```
Adding description to payload

2024-05-23 14:33 UTC, andrewhand commented on tests/unit/restapi/v1/conftest.py
> +    plugin_param_type1_response = actions.create_plugin_parameter_type(
```suggestion
    plugin_param_type1_response = actions.register_plugin_parameter_type(
```
Change create to register to keep established naming schema.

2024-05-23 14:33 UTC, andrewhand commented on tests/unit/restapi/v1/conftest.py
> +        structure="",
```suggestion
        client,
        name="int",
        group_id=auth_account["default_group_id"],
        structure="",
        description="The first parameter type.",
```
Adding description that is queried in tests.

2024-05-23 14:33 UTC, andrewhand commented on tests/unit/restapi/v1/conftest.py
> +    )
> actions return `TestResponse` but the fixture should return a `dict`, so append `.get_json()` to each `create_plugin_parameter_type` call here.
```suggestion
    ).get_json()
```

2024-05-23 14:33 UTC, andrewhand commented on tests/unit/restapi/v1/conftest.py
> +    )
> actions return `TestResponse` but the fixture should return a `dict`, so append `.get_json()` to each `create_plugin_parameter_type` call here.
```suggestion
    ).get_json()
```

2024-05-23 14:33 UTC, andrewhand commented on tests/unit/restapi/v1/conftest.py
> +    )
> actions return `TestResponse` but the fixture should return a `dict`, so append `.get_json()` to each `create_plugin_parameter_type` call here.
```suggestion
    ).get_json()
```

2024-05-23 14:33 UTC, andrewhand commented on tests/unit/restapi/v1/conftest.py
> +        structure="",
```suggestion
        client,
        name="string",
        group_id=auth_account["default_group_id"],
        structure="",
        description="Not retrieved.",
```
Add description for a param type that isn't queried.

2024-05-23 14:33 UTC, andrewhand commented on tests/unit/restapi/v1/conftest.py
> +        structure="",
```suggestion
        client,
        name="integer",
        group_id=auth_account["default_group_id"],
        structure="",
        description="The second parameter type.",
```
Adding description that is queried in tests.

2024-05-23 20:02 UTC, mtrapnell-nist commented
@andrewhand  I applied all the necessary changes for conftest.py and actions.py, so they should be ready for you to use on your branch.

2024-06-11 20:15 UTC, mtrapnell-nist commented
@keithmanville 
This includes all changes for the service layer for plugin parameter types and is ready for review.

2024-06-14 21:20 UTC, merged