feat: add draft commit workflow
usnistgov/dioptra pull request #681
Opened 2024-11-22 19:41 UTC by keithmanville

2025-01-24 16:58 UTC, keithmanville commented on src/dioptra/restapi/v1/utils.py
> +def build_resource(resource_type: str, resource_dict: dict) -> Any:
If this isn't being used, remove it.

2025-03-28 17:21 UTC, jkglasbrenner requested changes
Overall this looks good, the new code is nicely organized and easy to follow. My comments/questions are pretty minor, so they should be quick to address.

2025-03-28 17:21 UTC, jkglasbrenner commented on tests/unit/restapi/lib/routines.py
> +    commit_response = workflow_client.commit_draft(draft_response["id"]).json()
This is testing the failure path when the starting resource id and the current resource id are out of sync, yes? If so, add a code comment to indicate that's what's going on and differentiate it from the success path that follows it.

2025-03-31 14:20 UTC, keithmanville commented on tests/unit/restapi/lib/routines.py
> +    commit_response = workflow_client.commit_draft(draft_response["id"]).json()
yup, that's right. added a comment explaining [b3d6710](https://github.com/usnistgov/dioptra/pull/681/commits/b3d6710c89c93cc66c46006ebafb1d70587f5868)

2025-03-31 14:21 UTC, keithmanville commented on src/dioptra/restapi/v1/workflows/lib/views.py
> +    return db.session.scalar(resource_stmt)
It should, good catch. [1930de8](https://github.com/usnistgov/dioptra/pull/681/commits/1930de8bfc8fe72386f44cee8b1426e441d30a89)

2025-03-31 14:21 UTC, keithmanville commented on src/dioptra/restapi/v1/shared/resource_service.py
> +        """
resolved the inaccurate docstrings here: [f2de6d7](https://github.com/usnistgov/dioptra/pull/681/commits/f2de6d7b95b3221886afd51ff2e570ccb22212c7)

2025-04-02 13:27 UTC, merged