feat(restapi): add snapshot id to draft modifications PUT endpoints
usnistgov/dioptra pull request #707
Opened 2024-12-31 15:49 UTC by keithmanville

This commit adds an optional query parameter for changing a draft modifications base snapshot ID to the PUT endpoint. If a snapshot ID is provided the value is updated, otherwise it is left unchanged.

This feature is designed to enable the reconciliation of drafts by allowing the user to signal that their changes are based on a more recent snapshot.

An existing test is modified to test this feature.

2024-12-31 15:59 UTC, keithmanville commented
I ended up implementing this feature with an optional query parameter instead of adding a field alongside the draft data fields. The originally approach ended up feeling messy and adding complexity. It required dynamically modifying schemas in the draft controller. It also put the snapshot ID along with the data fields, which I felt was a bit confusing and makes it so the PUT data for drafts and their underlying resources not longer matched. Internally, resource snapshot is stored in the payload field, but in the responses it is broken out and only the draft data is in the payload. This is another reason it felt more natural to keep the snapshot ID separate for the request.

Do we want to validate that the submitted snapshot actually exists? This would require an extra query in the service layer. Right now it will accept any integer (validated by the schema). Once the draft commit workflow is merged, an attempt to commit a draft based on a non-existent snapshot would result in a 404 error from the commit endpoint.

Right now the test simply sets an arbitrary non-existent snapshot ID to verify it was changed. I think the test can be improved once commit workflow is done since that is the real user story for this feature (attempt to commit, update base snapshot ID, re-attempt commit).

2025-01-14 17:45 UTC, keithmanville commented
After group discussion we determined that the implementation should be changed so that the snapshot ID be provided as part of the payload, not a query param. There should be a new draft schema that envelops the resource schemas and includes the snapshot ID external to the resource data.

2025-01-16 15:53 UTC, keithmanville commented
This is a breaking change to the draft modifications PUT endpoints.

The client is updated for this change, but the UI needs to be updated as well.

2025-01-16 20:07 UTC, keithmanville commented
For now the UI simply passes the current snapshot ID when modifying draft modifications to a queue. In the future we will want to make this part of the form. I recommend leaving this for when we design the UI around reconciling drafts.

2025-01-24 16:19 UTC, keithmanville commented on src/dioptra/restapi/v1/queues/controller.py
> +
remove this extra line

2025-01-24 16:38 UTC, keithmanville commented on tests/unit/restapi/v1/test_queue.py
> +    draft = {
revert formatting changes

2025-01-24 16:38 UTC, keithmanville commented on src/dioptra/restapi/v1/shared/drafts/service.py
> +        draft.payload["resource_snapshot_id"] = payload["resource_snapshot_id"]
add check here to query for resource snapshot id to ensure it exists and that it is of the correct resource type. Also add check to enforce that the provided resource snapshot ID is >= the existing resource snapshot ID.

2025-01-24 16:38 UTC, keithmanville commented on src/dioptra/restapi/v1/shared/drafts/service.py
> +        draft.payload["resource_snapshot_id"] = payload["resource_snapshot_id"]
add temporary check that forces the new snapshot ID to be the same. This effectively prevents this new feature from being used. This check will be removed when the draft commit workflow feature is added.

2025-01-24 16:38 UTC, jkglasbrenner requested changes

2025-01-24 16:38 UTC, jkglasbrenner commented on src/dioptra/client/drafts.py
>          Args:
Client docstring needs to be updated.

2025-01-24 16:42 UTC, keithmanville commented
Make sure to update docstrings to reflect new keyword args for ModifyResourceDraftsSubCollectionClient modify function.
This can be found in most subcollection clients.

Example for queues:
https://github.com/usnistgov/dioptra/blob/d307312b6a9d90c6c0b8e51a5a9fd569088d7d09/src/dioptra/client/queues.py#L116

2025-01-28 15:20 UTC, jkglasbrenner approved these changes
LGTM

2025-01-29 18:10 UTC, merged